name: run-tests
on:
  push:
    branches:
      -main
  pull_request:
    types:[opened,synchronize,reopened]
jobs:
  build:
    name: run-api-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 11



      - name: Run API tests
        run: mvn clean test
